/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Tea = new javax.swing.JCheckBox();
        ITea = new javax.swing.JCheckBox();
        Latte = new javax.swing.JCheckBox();
        Americano = new javax.swing.JCheckBox();
        CC = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        TeaV = new javax.swing.JTextField();
        ITeaV = new javax.swing.JTextField();
        LatteV = new javax.swing.JTextField();
        CCV = new javax.swing.JTextField();
        AmericanoV = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Pizza = new javax.swing.JCheckBox();
        PR = new javax.swing.JCheckBox();
        PW = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        PizzaV = new javax.swing.JTextField();
        PRV = new javax.swing.JTextField();
        PWV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cafe Management System");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Beverage"));
        jPanel1.setToolTipText("");

        Tea.setText("Tea");
        Tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaActionPerformed(evt);
            }
        });

        ITea.setText("Ice Tea");

        Latte.setText("Latte");

        Americano.setText("Americano");

        CC.setText("Cold Coffee");
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tea)
                            .addComponent(ITea)
                            .addComponent(Latte)
                            .addComponent(Americano))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CC)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Tea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ITea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Latte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Americano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CC)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantity"));

        TeaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeaVActionPerformed(evt);
            }
        });

        ITeaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ITeaVActionPerformed(evt);
            }
        });

        LatteV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LatteVActionPerformed(evt);
            }
        });

        CCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCVActionPerformed(evt);
            }
        });

        AmericanoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmericanoVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CCV, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(AmericanoV)
                    .addComponent(LatteV)
                    .addComponent(ITeaV)
                    .addComponent(TeaV))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TeaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(ITeaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LatteV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AmericanoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Snacks"));
        jPanel3.setAutoscrolls(true);

        Pizza.setText("Pizza");
        Pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaActionPerformed(evt);
            }
        });

        PR.setText("Pasta Red");

        PW.setText("Pasta White");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pizza)
            .addComponent(PR)
            .addComponent(PW)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pizza)
                .addGap(5, 5, 5)
                .addComponent(PR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PW)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantity"));

        PizzaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PizzaVActionPerformed(evt);
            }
        });

        PRV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRVActionPerformed(evt);
            }
        });

        PWV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PRV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(PizzaV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PWV))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PizzaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PRV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PWV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );

        jButton1.setText("Confirm Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset Order");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("New Order");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Total Amount:");

        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(92, 92, 92))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeaActionPerformed

    private void TeaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeaVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeaVActionPerformed

    private void ITeaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ITeaVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ITeaVActionPerformed

    private void LatteVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LatteVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LatteVActionPerformed

    private void CCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCVActionPerformed

    private void AmericanoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmericanoVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmericanoVActionPerformed

    private void PizzaVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PizzaVActionPerformed

    private void PRVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRVActionPerformed

    private void PWVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PWVActionPerformed

    private void PizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PizzaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            Login AL=new Login();
            AL.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Tea.setSelected(false);
        ITea.setSelected(false);
        CC.setSelected(false);
        Latte.setSelected(false);
        Americano.setSelected(false);
        Pizza.setSelected(false);
        PW.setSelected(false);
        PR.setSelected(false);
        TeaV.setText("");
        ITeaV.setText("");
        CCV.setText("");
        LatteV.setText("");
        AmericanoV.setText("");
        PizzaV.setText("");
        PWV.setText("");
        PRV.setText("");  
        amount.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Tea.setSelected(false);
        ITea.setSelected(false);
        CC.setSelected(false);
        Latte.setSelected(false);
        Americano.setSelected(false);
        Pizza.setSelected(false);
        PW.setSelected(false);
        PR.setSelected(false);
        TeaV.setText("");
        ITeaV.setText("");
        CCV.setText("");
        LatteV.setText("");
        AmericanoV.setText("");
        PizzaV.setText("");
        PWV.setText("");
        PRV.setText("");  
        amount.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
       Class.forName("java.sql.Driver");    
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/cafe","root","circinus");
       Statement stmt = con.createStatement();
       double amt=0;
       String items="";
        if(Tea.isSelected()){
            String query="SELECT * FROM MENU WHERE ITEM= 'TEA';";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            double price = rs.getDouble("PRICE");
            int x = Integer.parseInt(TeaV.getText());
            amt = amt + x*price;
            items = items + "Tea ("+TeaV.getText()+"), ";
            }
        }
        if(ITea.isSelected()){
            String query="SELECT * FROM MENU WHERE ITEM= 'ICE TEA';";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            double price = rs.getDouble("PRICE");
            int x = Integer.parseInt(ITeaV.getText());
            amt = amt + x*price;
            items = items + "Ice Tea ("+ITeaV.getText()+"), ";
            }
        }
        if(CC.isSelected()){
           String query="SELECT * FROM MENU WHERE ITEM= 'COLD COFFEE';";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            double price = rs.getDouble("PRICE");
            int x = Integer.parseInt(CCV.getText());
            amt = amt + x*price;
            items = items + "Cold Coffee ("+CCV.getText()+"), ";
            }
        }
        if(Latte.isSelected()){
            String query="SELECT * FROM MENU WHERE ITEM= 'LATTE';";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            double price = rs.getDouble("PRICE");
            int x = Integer.parseInt(LatteV.getText());
            amt = amt + x*price;
            items = items + "Latte ("+LatteV.getText()+"), ";
            }
        }
        if(Americano.isSelected()){
            String query="SELECT * FROM MENU WHERE ITEM= 'AMERICANO';";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            double price = rs.getDouble("PRICE");
            int x = Integer.parseInt(AmericanoV.getText());
            amt = amt + x*price;
            items = items + "Americano ("+AmericanoV.getText()+"), ";
            }
        }
        if(Pizza.isSelected()){
            String query="SELECT * FROM MENU WHERE ITEM= 'PIZZA';";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            double price = rs.getDouble("PRICE");
            int x = Integer.parseInt(PizzaV.getText());
            amt = amt + x*price;
            items = items + "Pizza ("+PizzaV.getText()+"), ";
            }
        }
        if(PW.isSelected()){
            String query="SELECT * FROM MENU WHERE ITEM= 'PASTA WHITE';";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            double price = rs.getDouble("PRICE");
            int x = Integer.parseInt(PWV.getText());
            amt = amt + x*price;
            items = items + "Pasta White ("+PWV.getText()+"), ";
            }
        }
        if(PR.isSelected()){
            String query="SELECT * FROM MENU WHERE ITEM= 'PASTA RED';";
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            while(rs.next()){
            double price = rs.getDouble("PRICE");
            int x = Integer.parseInt(PRV.getText());
            amt = amt + x*price;
            items = items + "Pasta Red ("+PRV.getText()+"), ";
            }
        }
        amount.setText(""+amt);
        String strSQL= "INSERT INTO ORDERS (ITEMS,AMOUNT) VALUES ('"+items+"','"+amt+"')";
        int rowsEffected = stmt.executeUpdate(strSQL);
        JOptionPane.showMessageDialog(this,"Order Placed!\n\n Total Amount: Rs:"+amt+"/-");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Order Failed!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Console a = new Console();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Americano;
    private javax.swing.JTextField AmericanoV;
    private javax.swing.JCheckBox CC;
    private javax.swing.JTextField CCV;
    private javax.swing.JCheckBox ITea;
    private javax.swing.JTextField ITeaV;
    private javax.swing.JCheckBox Latte;
    private javax.swing.JTextField LatteV;
    private javax.swing.JCheckBox PR;
    private javax.swing.JTextField PRV;
    private javax.swing.JCheckBox PW;
    private javax.swing.JTextField PWV;
    private javax.swing.JCheckBox Pizza;
    private javax.swing.JTextField PizzaV;
    private javax.swing.JCheckBox Tea;
    private javax.swing.JTextField TeaV;
    private javax.swing.JLabel amount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
